---
title: Lowkey
timezone: UTC
collections:
  category:
    output: true
  posts:
    title: Posts
    output: true
  specials:
    title: Specials
    output: true
specials_list:
  - "hindsight2018"
  - "concise21"
title_long: Lowkey | A blog by Matthew Wang
email: matt@matthewwang.me
author:
  name: Matthew Wang
  twitter: welcomemattwang
description: "The blog of one of the more boring people named Matthew Wang.

"
baseurl: ''
url: https://blog.matthewwang.me
twitter:
  username: welcomemattwang
github: mattxwang
repo: http://github.com/mattxwang/lowkey
website: https://matthewwang.me
logo: "/img/logo.png"
markdown: kramdown
kramdown:
  parse_block_html: true
exclude:
  - vendor
  - LICENSE.md
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - .gitignore
  - .sass-cache
  - .git
  - .github
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 10

words_read_per_minute: 180
